channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - eccodes
  - ffmpeg
  - hdf5
  - ipykernel
  - netcdf4<1.6.1
  - openh264
  - python=3.9
  - pip
  - xarray
  - pip:
    - model-ensembler
