channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - cartopy
  - cfgrib
  - cudatoolkit
  - cudnn
  - dask
  - distributed
  - eccodes
  - h5py
  - hdf4
  - hdf5
  - imageio
  - imageio-ffmpeg
  - ipykernel
  - iris
  - netcdf4
  - plotly
  - pip
  - python==3.8
  - setuptools
  - tensorboard
  - tensorflow=2.4.1=gpu_py38h8a7d6ce_0
  - wheel
  - xarray
  - pip:
    - azure-storage-blob
    - cdsapi
    - dm-tree
    - ecmwf-api-client
    - gast==0.3.3
    - model-ensembler
    - tensorflow-probability
