channels:
  - conda-forge
dependencies:
  - cartopy
  - cudatoolkit
  - cudnn
  - eccodes
  - ffmpeg
  - hdf5
  - ipykernel
  - netcdf4<1.6.1
  - openh264
  - python=3.9
  - pip
  - xarray
  - pip:
    - model-ensembler
