---
ensemble:
  vars:
    arg_dataset:    laptop
    arg_batch:      1
    arg_queue:      1
    arg_strategy:   default
    arg_epochs:     10
    arg_filter_factor:  0.3
    prep:           ""
    symlinks:
      - ../../../train.py
      - ../../../loader.laptop.json
      - ../../../dataset_config.laptop.json
      - ../../../network_datasets
      - ../../../results
    gpus:         1
    mem:          128gb

  pre_process:
    - name:   execute
      args:
        cmd:  mkdir -p results/networks

  post_process: []

  batch_config:
    templatedir:  ../template
    templates:
    - icenet_train.sh.j2
    email:        jambyr@bas.ac.uk
    job_file:     icenet_train.sh
    cluster:      gpu
    nodes:        1
    ntasks:       4
    length:       02:00:00
    maxruns:      2
    maxjobs:      1

  batches:
    - name:       laptop
      basedir:    ./ensemble/laptop
      pre_batch:  []
      pre_run:    []
      runs:
        - seed:   42
        - seed:   43
        - seed:   44
        - seed:   45
        - seed:   46
      post_run:   []
      post_batch:
        - name:   execute
          args:
            cmd:  python ../../postprocess.train.py


