---
ensemble:
  vars:
    arg_dataset:    ensemble_22
    arg_batch:      4
    arg_queue:      2
    arg_strategy:   default
    arg_epochs:     100
    arg_filter_factor:  1
    prep: |
      module load hpc/cuda/11.2
      . /hpcpackages/python/miniconda3/etc/profile.d/conda.sh
      conda activate /data/hpcdata/users/jambyr/miniconda3/envs/icenet2
    symlinks:
      - ../../../train.py
      - ../../../loader.ensemble_split.json
      - ../../../dataset_config.ensemble_22.json
      - ../../../network_datasets
      - ../../../results
    gpus:         1
    mem:          192gb
    nodelist:     node022

  pre_process:
    - name:   execute
      args:
        cmd:  mkdir -p ./results/networks

  post_process: []

  batch_config:
    templatedir:  ../template
    templates:
    - icenet_train.sh.j2
    email:        jambyr@bas.ac.uk
    job_file:     icenet_train.sh
    cluster:      gpu
    nodes:        1
    ntasks:       8
    length:       2-00:00:00
    maxruns:      3
    maxjobs:      1

  batches:
    - name:       blue
      basedir:    ./ensemble/blue
      pre_batch:  []
      pre_run:    []
      runs:
        - seed:   42
        - seed:   43
        - seed:   44
        - seed:   45
        - seed:   46
      post_run:   []
      post_batch:
        - name:   execute
          args:
            cmd:  python ../../postprocess.train.py


