---
ensemble:
  vars:     {}
  pre_process: []
  post_process: []

  batch_config:
    templatedir:  ../../../ensemble/template
    templates:
    - slurm_run.sh.j2
    email:        jambyr@bas.ac.uk
    job_file:     slurm_run.sh
    cluster:      gpu
    nodes:        1
    ntasks:       4
    length:       02:00:00
    maxruns:      6
    maxjobs:      6
    pre_batch:    []
    pre_run:      []
    runs:
      - seed: 42
      - seed: 43
      - seed: 44
      - seed: 45
      - seed: 46
    post_run:     []
    post_batch:   []

  batches:
    - name:       draft
      basedir: ./ensemble/baseline
      pre_batch:  []
      post_batch: []
      gpus:       1
      mem:        96gb
      arg_dataset:    training
      arg_size:       4
      arg_strategy:   default
      arg_epoch:      10
