---
ensemble:
  vars:
    arg_batch:          4
    arg_dataset:        DATASET
    arg_epochs:         100
    arg_filter_factor:  1
    arg_queue:          2
    arg_prep:           local.sh 
    arg_strategy:       default
    symlinks:
      - ../../../data
      - ../../../ENVS*
      - ../../../loader.LOADER.json
      - ../../../dataset_config.DATASET.json
      - ../../../network_datasets
      - ../../../processed
      - ../../../results
    gpus:         1
    mem:          128gb

  pre_process:
    - name:   execute
      args:
        cmd:  mkdir -p ./results/networks

  post_process: []

  batch_config:
    templatedir:  ../template
    templates:
    - icenet_train.sh.j2
    email:        someone@example.com
    job_file:     icenet_train.sh
    cluster:      gpu
    nodes:        1
    ntasks:       NTASKS
    length:       4-00:00:00
    maxruns:      5
    maxjobs:      MAXJOBS

  batches:
    - name:       NAME
      basedir:    ./ensemble/NAME
      pre_batch:  []
      pre_run:    []
      runs:
        - seed:   42
        - seed:   46
        - seed:   45
        - seed:   17
        - seed:   24
        - seed:   84
        - seed:   83
        - seed:   16
        - seed:   5
        - seed:   3
      post_run:   []
      post_batch:
        - name:   execute
          args:
            cmd:  /usr/bin/echo "No postprocessing in place for training ensemble"


