---
ensemble:
  vars:
    batch:          4
    cluster:        dummy
    dataset:        DATASET
    email:          someone@example.com
    epochs:         100
    filter_factor:  1
    gpus:           1
    length:         1-00:00:00
    mem:            128gb
    nodes:          1
    ntasks:         2
    preload:        DATASET
    strategy:       default
    symlinks:
      - ../../../data
      - ../../../ENVS*
      - ../../../LOADER
      - ../../../DATASET
      - ../../../network_datasets
      - ../../../processed
      - ../../../results

  pre_process:
    - name:   execute
      args:
        cmd:  mkdir -p ./results/networks

  post_process: []

  batch_config:
    templatedir:  ../template
    templates:
    - icenet_train.sh.j2
    job_file:     icenet_train.sh
    maxruns:      MAXJOBS
    maxjobs:      MAXJOBS

  batches:
    - name:       NAME
      basedir:    ./ensemble/NAME
      pre_batch:  []
      pre_run:    []
      runs:
        - seed:   SEEDS
      post_run:   []
      post_batch:
        - name:   execute
          args:
            cmd:  /usr/bin/echo "No postprocessing in place for training ensemble"


